Add check for genomic interval creation
This adds in a check for genomic interval creation which sometimes fails when the `ulimit` is not high enough.  This should clearly terminate dDocent upon error.

diff --git a/dDocent b/dDocent
--- a/dDocent
+++ b/dDocent
@@ -3,7 +3,7 @@ export LC_ALL=en_US.UTF-8
 export SHELL=bash
 
 ##########dDocent##########
-VERSION='2.9.2'; export VERSION
+VERSION='2.9.3'; export VERSION
 #This script serves as an interactive bash wrapper to QC, assemble, map, and call SNPs from double digest RAD (SE or PE), ezRAD (SE or PE) data, or SE RAD data.
 #It requires that your raw data are split up by tagged individual and follow the naming convention of:
 
@@ -503,6 +503,13 @@ if [ "$SNP" != "no" ]; then
 	else if (cov > cutoff && lc < tt ) {i=i+1; x="mapped."i".bed"; print $1"\t"$2"\t"$3 > x; cov=lc;e=0}
 	}'
 		
+	if [ $? -eq 0 ]; then 
+		echo "Genomic interval creation completed successfully."
+	else
+		echo "Genomic interval creation failed.  This may be related to the maximum number of open files."
+		exit 1
+	fi
+	
 	FB2=$(( $NUMProc / 8 ))
 	export FB2
 	echo -e "\nUsing FreeBayes to call SNPs"
