Update to test version of 2.3
Now, dDocent has a built in way of detecting memory problems with FreeBayes and then reconfiguring run parameters to conserve memory.

diff --git a/dDocent b/dDocent
--- a/dDocent
+++ b/dDocent
@@ -2,7 +2,7 @@
 export LC_ALL=en_US.UTF-8
 
 ##########dDocent##########
-VERSION='2.2.25'
+VERSION='2.3.0'
 #This script serves as an interactive bash wrapper to QC, assemble, map, and call SNPs from double digest RAD (SE or PE), ezRAD (SE or PE) data, or SE RAD data.
 #It requires that your raw data are split up by tagged individual and follow the naming convention of:
 
@@ -368,7 +368,7 @@ if [ "$SNP" != "no" ]; then
 	}' 
 	
 	FB2=$(( $NUMProc / 4 ))
-
+	export FB2
 	echo "Using FreeBayes to call SNPs"
 
 	#Creates a population file to use for more accurate genotype calling
@@ -381,17 +381,58 @@ if [ "$SNP" != "no" ]; then
 
 ###New implementation of SNP calling here to save on memory	
 	call_genos(){
-	samtools view -@$FB2 -b -1 -L mapped.$1.bed -o split.$1.bam cat-RRG.bam
-	samtools index split.$1.bam
-	freebayes -b split.$1.bam -t mapped.$1.bed -v raw.$1.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 10
-	rm split.$1.bam*
+	if [ -f "freebayes.error" ]; then 
+		echo "A previous freebayes instance failed.  Skipping for later re-run"
+	else
+		samtools view -@$FB2 -b -1 -L mapped.$1.bed -o split.$1.bam cat-RRG.bam
+		samtools index split.$1.bam
+		freebayes -b split.$1.bam -t mapped.$1.bed -v raw.$1.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 10
+		if [ $? -eq 0 ]; then
+    			echo "This freebayes instance completed successfully."
+		else
+    			echo "ERROR: freebayes instance DID NOT COMPLETE"
+			echo $? > freebayes.error
+			exit 1
+		fi	
+		rm split.$1.bam*
+	fi
 	}
 	export -f call_genos
 
-	ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --env call_genos --memfree $MAXMemory -j $NUMProc --no-notice call_genos {}
-####	
-	#ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --memfree $MAXMemory -j $FB1 --no-notice --delay 1 freebayes -L bamlist.list -t mapped.{}.bed -v raw.{}.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 10
-	#ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --memfree $MAXMemory -j $FB1 --no-notice "samtools view -b -L mapped.{}.bed | freebayes -c -t mapped.{}.bed -v raw.{}.vcf -f reference.fasta -m 5 -q 5 -E 3 --min-repeat-entropy 1 -V --populations popmap -n 10"
+	ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --halt now,fail=1 --env call_genos --memfree $MAXMemory -j $NUMProc --no-notice call_genos {}
+
+
+	if [ -f "freebayes.error" ]; then
+                echo "A previous freebayes instance failed.  dDocent will now recalibrate run parameters to use less memory."
+		rm mapped.*.bed
+		rm freebayes.error
+		LIM=$(( $NUMProc * 4 ))
+        	if head -1 reference.fasta | grep -e 'dDocent' reference.fasta 1>/dev/null; then
+
+                	DP=$(mawk '{print $4}' cov.stats | sort -rn | perl -e '$d=.001;@l=<>;print $l[int($d*@l)]')
+                	CC=$( mawk -v x=$DP '$4 < x' cov.stats | mawk '{len=$3-$2;lc=len*$4;tl=tl+lc} END {OFMT = "%.0f";print tl/"'$LIM'"}')
+        	else
+                	DP=$(mawk '{print $4}' cov.stats | sort -rn | perl -e '$d=.00005;@l=<>;print $l[int($d*@l)]')
+                	CC=$( mawk -v x=$DP '$4 < x' cov.stats | mawk '{len=$3-$2;lc=len*$4;tl=tl+lc} END {OFMT = "%.0f";print tl/"'$LIM'"}')
+        	fi
+        	mawk -v x=$DP '$4 < x' cov.stats |sort -V -k1,1 -k2,2 | mawk -v cutoff=$CC 'BEGIN{i=1}
+        	{ len=$3-$2;lc=len*$4;cov = cov + lc
+        	if ( cov < cutoff) {x="mapped."i".bed";print $1"\t"$2"\t"$3 > x}
+        	else {i=i+1; x="mapped."i".bed"; print $1"\t"$2"\t"$3 > x; cov=0}
+        	}'
+
+        	FB2=$(( $NUMProc / 10 ))
+        	export FB2
+		echo "Using FreeBayes to call SNPs"
+		NumP=$(( $NUMProc / 2 ))
+		ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --halt now,fail=1 --env call_genos --memfree $MAXMemory -j $NumP --no-notice call_genos {}
+        fi
+	
+	if [ -f "freebayes.error" ]; then
+		echo "FreeBayes has now failed a second time, likely because of memory issues.  More resources must be allocated to finish this analysis."
+		ERROR3=1
+		export ERROR3
+	fi	
 
 
 	rm mapped.*.bed 
@@ -424,7 +465,7 @@ if [ "$MAP" != "no" ]; then
 ERROR1=$(mawk '/developer/' bwa* 2>/dev/null | wc -l 2>/dev/null) 
 fi
 ERROR2=$(mawk '/error/' *.bam.log 2>/dev/null | wc -l 2>/dev/null)
-ERRORS=$(($ERROR1 + $ERROR2))
+ERRORS=$(($ERROR1 + $ERROR2 + $ERROR3))
 
 #Move various log files to own directory
 if [ ! -d "logfiles" ]; then
