version 2.2.8
1.  Update bedtools dependency to accept multiple program versions
2.  Better parallelization of read trimming
3.  Fix encoding for decimal separators

diff --git a/dDocent b/dDocent
--- a/dDocent
+++ b/dDocent
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
-export LC_ALL=C.UTF8
+export LC_ALL=en_US.UTF-8
 
 ##########dDocent##########
-VERSION='2.2.7'
+VERSION='2.2.8'
 #This script serves as an interactive bash wrapper to QC, assemble, map, and call SNPs from double digest RAD (SE or PE), ezRAD (SE or PE) data, or SE RAD data.
 #It requires that your raw data are split up by tagged individual and follow the naming convention of:
 
@@ -15,7 +15,7 @@ echo -e "Contact jpuritz@gmail.com with any problems \n\n "
 ###Code to check for the required software for dDocent
 
 echo "Checking for required software"
-DEP=(freebayes mawk bwa samtools vcftools rainbow gnuplot gawk seqtk cd-hit-est bamToBed bedtools coverageBed parallel vcfcombine bamtools pearRM)
+DEP=(freebayes mawk bwa samtools vcftools rainbow gnuplot gawk seqtk cd-hit-est bamToBed bedtools parallel vcfcombine bamtools pearRM)
 NUMDEP=0
 for i in "${DEP[@]}"
 do
@@ -90,13 +90,17 @@ VCFTV=$(vcftools | grep VCF | grep -oh '[0-9]*[a-z]*)$' | sed 's/[a-z)]//')
                 VCFGTFLAG="--max-missing"
 	fi
 
-BTC=$( bedtools --version | mawk '{print $2}' | sed 's/v//g' | cut -f1,2 -d"." )
-	if [ "$BTC" != "2.23" ]; then
+BTC=$( bedtools --version | mawk '{print $2}' | sed 's/v//g' | cut -f1,2 -d"." | sed 's/2\.//g' )
+	if [ "$BTC" -ge "26" ]; then
+		BEDTOOLSFLAG="NEW"
+		elif [ "$BTC" == "23" ]; then
+		BEDTOOLSFLAG="OLD"
+		elif [ "$BTC" != "23" ]; then
 		echo "The version of bedtools installed in your" '$PATH' "is not optimized for dDocent."
-		echo "Please install only version 2.23.0"
-		exit 1
+		echo "Please install version 2.23.0 or version 2.26.0 and above"
+		exit 1	
 	fi
-
+		
 if ! awk --version | fgrep -v GNU &>/dev/null; then
          awk=gawk
     else
@@ -319,9 +323,13 @@ if [ "$SNP" != "no" ]; then
 	#This code estimates the coverage of reference intervals and removes intervals in 0.01% of depth
 	#This allows genotyping to be more effecient and eliminates extreme copy number loci from the data
 	if [ "cat-RRG.bam" -nt "cov.stats" ]; then
-		coverageBed -abam cat-RRG.bam -b mapped.bed -counts > cov.stats
+		if [ "$BEDTOOLSFLAG" == "OLD" ]; then
+			coverageBed -abam cat-RRG.bam -b mapped.bed -counts > cov.stats
+		else
+			bedtools coverage -b  cat-RRG.bam -a mapped.bed -counts > cov.stats
+		fi
 	fi
-	
+		
 	if head -1 reference.fasta | grep -e 'dDocent' reference.fasta 1>/dev/null; then
 	
 		DP=$(mawk '{print $4}' cov.stats | sort -rn | perl -e '$d=.001;@l=<>;print $l[int($d*@l)]')
@@ -405,9 +413,9 @@ mv *.txt *.log log ./logfiles 2> /dev/null
 #Sending a completion email
 
 if [ $ERRORS -gt 0 ]; then
-        echo -e "dDocent has finished with errors in" `pwd` "\n\ndDocent started" $STARTTIME "\n\ndDocent finished" `date` "\n\nPlease check log files\n\n" `mawk '/After filtering, kept .* out of a possible/' ./logfiles/Final.log` "\n\ndDocent" $VERSION "\nThe 'd' is silent, hillbilly." | mailx -s "dDocent has finished with ERRORS!" $MAIL
+        echo -e "dDocent has finished with errors in" `pwd` "\n\ndDocent started" $STARTTIME "\n\ndDocent finished" `date` "\n\nPlease check log files\n\n" `mawk '/After filtering, kept .* out of a possible/' ./logfiles/VCFtools.log` "\n\ndDocent" $VERSION "\nThe 'd' is silent, hillbilly." | mailx -s "dDocent has finished with ERRORS!" $MAIL
 else
-        echo -e "dDocent has finished with an analysis in" `pwd` "\n\ndDocent started" $STARTTIME "\n\ndDocent finished" `date` "\n\n" `mawk '/After filtering, kept .* out of a possible/' ./logfiles/Final.log` "\n\ndDocent" $VERSION "\nThe 'd' is silent, hillbilly." | mailx -s "dDocent has finished" $MAIL
+        echo -e "dDocent has finished with an analysis in" `pwd` "\n\ndDocent started" $STARTTIME "\n\ndDocent finished" `date` "\n\n" `mawk '/After filtering, kept .* out of a possible/' ./logfiles/VCFtools.log` "\n\ndDocent" $VERSION "\nThe 'd' is silent, hillbilly." | mailx -s "dDocent has finished" $MAIL
 fi
 
 
@@ -444,14 +452,17 @@ echo $MAIL >> dDocent.runs
 
 #Function for trimming reads using trimmomatic
 TrimReads () { 
-for i in "${NAMES[@]}";
-	do
-        zcat $i.F.fq.gz | head -2 | tail -1 >> lengths.txt
-        done	
-        MLen=$(mawk '{ print length() | "sort -rn" }' lengths.txt| head -1)
-        MLen=$(($MLen / 2))
+
+	cat namelist | parallel "zcat {}.F.fq.gz | head -2 | tail -1 >> lengths.txt"
+	MLen=$(mawk '{ print length() | "sort -rn" }' lengths.txt| head -1)
+    MLen=$(($MLen / 2))
 	TW="MINLEN:$MLen"
-	
+	if [ -f $i.R.fq.gz ]; then
+		cat namelist | parallel java -jar $TRIMMOMATIC PE -threads 2 -phred33 {}.F.fq.gz {}.R.fq.gz {}.R1.fq.gz {}.unpairedF.fq.gz {}.R2.fq.gz {}.unpairedR.fq.gz ILLUMINACLIP:$ADAPTERS:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:5:10 $TW &> {}.trim.log
+		else cat namelist | parallel java -jar $TRIMMOMATIC SE -threads 2 -phred33 {}.F.fq.gz {}.R1.fq.gz ILLUMINACLIP:$ADAPTERS:2:30:10 LEADING:20 TRAILING:20 SLIDINGWINDOW:5:10 $TW &> {}.trim.log
+	fi 
+
+
 for i in "${NAMES[@]}"
 do
 #echo "Trimming Sample $i"
