Update dDocent

diff --git a/dDocent b/dDocent
--- a/dDocent
+++ b/dDocent
@@ -553,7 +553,7 @@ if [ "$SNP" != "no" ]; then
 	
 	rm freebayes.error freebayes.log &> /dev/null
 	
-	ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --bar --halt now,fail=5 --env call_genos --memfree $MAXMemory -j $NUMProc --no-notice "call_genos {} &>> temp.LOG && if [ $? -eq 1 ]; then echo -e "$?" "\t" "$1" >> freebayes.error; fi"
+	ls mapped.*.bed | sed 's/mapped.//g' | sed 's/.bed//g' | shuf | parallel --bar --halt now,fail=5 --env call_genos --memfree $MAXMemory -j $NUMProc --no-notice "call_genos {} && if [ $? -eq 1 ]; then echo -e "$?" "\t" {} >> freebayes.error; fi"
 
 
 	if [ -f "freebayes.error" ]; then
